name: CI - projet Cypress
on:
    push:
      branches: [Tavernier]
jobs:
    # linter:
    #     name: Verification EsLint
    #     runs-on: ubuntu-latest
    #     continue-on-error: true

    #     steps:
    #         - name: Checkout repository
    #           uses: actions/checkout@v3
    #         - name: Setup Node.js
    #           uses: actions/setup-node@v4
    #           with:
    #             node-version: 20
    #             cache: 'npm'
            
    #         - name: Install ESLint, Cypress plugin and globals
    #           run: npm install eslint eslint-plugin-cypress globals --save-dev --legacy-peer-deps

    #         - name: Run ESLint on project
    #           run: npx eslint "cypress/**/*.{ts,tsx}" "src/**/*.{ts,tsx}" -f html -o eslint-report.html
            
    #         - name: Upload ESLint reports
    #           uses: actions/upload-artifact@v4
    #           with:
    #             name: eslint-reports
    #             path: eslint-report.html

    # tests_cypress:
    #     runs-on: ubuntu-latest    
    #     continue-on-error: true
    #     steps:
    #         - name: Checkout repository
    #           uses: actions/checkout@v3
    #         - name: Setup Node.js
    #           uses: actions/setup-node@v4
    #           with:
    #             node-version: 20
    #             cache: 'npm'
    #         - name: install dependencies
    #           run: npm install --legacy-peer-deps
    #         - name: install allure
    #           run: npm install --save-dev @shelex/cypress-allure-plugin --legacy-peer-deps
    #         - name: install wait-on
    #           run: npm install --save-dev wait-on --legacy-peer-deps

    #         - name: Start frontend + API
    #           run: npm run dev &
    #         - name: Wait for frontend to be ready
    #           run: npx wait-on http://localhost:3000

    #         - name: Run Cypress Tests
    #           run: npx cypress run --env allure=true
    #         - name: Upload Allure Results
    #           uses: actions/upload-artifact@v4
    #           with:
    #             name: allure-results
    #             path: allure-results
              

    # check_dependencies:
    #     runs-on: ubuntu-latest
    #     steps:
    #       - name: Checkout repository
    #         uses: actions/checkout@v3
    #       - name: Install Snyk
    #         run: npm install -g snyk

    #       - name: Authenticate Snyk
    #         run: snyk auth ${{ secrets.SNYK_TOKEN }}

    #       - name: Run Snyk Test
    #         run: snyk test --severity-threshold=high --json > snyk-report.json
    #         continue-on-error: true

    #       - name: Upload Report
    #         uses: actions/upload-artifact@v4
    #         with:
    #           name: snyk-report
    #           path: snyk-report.json


    check_security:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v3
          - name: Setup Node.js
            uses: actions/setup-node@v4
            with:
              node-version: 20
              cache: 'npm'
          - name: install dependencies
            run: npm install --legacy-peer-deps
          - name: install wait-on
            run: npm install --save-dev wait-on --legacy-peer-deps

          - name: Start frontend + API
            run: npm run dev &
          - name: Wait for frontend to be ready
            run: npx wait-on http://localhost:3000
          - name: Active scan
            uses: zaproxy/action-baseline@v0.15.0
            with:
              target: "http://localhost:3000"
            continue-on-error: true
          - name: Upload Report
            uses: actions/upload-artifact@v4
            with:
              name: zap-report
              path: report_html.html


    # check_perf:
    #     runs-on: ubuntu-latest

    # check_vulnerability:
    #     runs-on: ubuntu-latest